"""add relationships

Revision ID: 92a5a23200a1
Revises: 177099392d6e
Create Date: 2025-02-06 11:42:53.206996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92a5a23200a1'
down_revision = '177099392d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'event', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'owner_id')
    # ### end Alembic commands ###
