"""modify fields in questions

Revision ID: c056988fac21
Revises: e863fcf5b668
Create Date: 2025-02-06 22:35:04.902636

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c056988fac21'
down_revision = 'e863fcf5b668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('question', sa.Column('attendee_identifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_constraint('question_owner_id_fkey', 'question', type_='foreignkey')
    op.drop_column('question', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('question_owner_id_fkey', 'question', 'user', ['owner_id'], ['id'])
    op.drop_column('question', 'attendee_identifier')
    op.drop_column('question', 'user_name')
    # ### end Alembic commands ###
